package com.example.framework.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.framework.dao.ShopcarMessage;

import com.example.framework.dao.ShopcarMessageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig shopcarMessageDaoConfig;

    private final ShopcarMessageDao shopcarMessageDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        shopcarMessageDaoConfig = daoConfigMap.get(ShopcarMessageDao.class).clone();
        shopcarMessageDaoConfig.initIdentityScope(type);

        shopcarMessageDao = new ShopcarMessageDao(shopcarMessageDaoConfig, this);

        registerDao(ShopcarMessage.class, shopcarMessageDao);
    }
    
    public void clear() {
        shopcarMessageDaoConfig.clearIdentityScope();
    }

    public ShopcarMessageDao getShopcarMessageDao() {
        return shopcarMessageDao;
    }

}
