package com.shopmall.bawei.framework.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.shopmall.bawei.framework.dao.ShopCarMessage;

import com.shopmall.bawei.framework.dao.ShopCarMessageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig shopCarMessageDaoConfig;

    private final ShopCarMessageDao shopCarMessageDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        shopCarMessageDaoConfig = daoConfigMap.get(ShopCarMessageDao.class).clone();
        shopCarMessageDaoConfig.initIdentityScope(type);

        shopCarMessageDao = new ShopCarMessageDao(shopCarMessageDaoConfig, this);

        registerDao(ShopCarMessage.class, shopCarMessageDao);
    }
    
    public void clear() {
        shopCarMessageDaoConfig.clearIdentityScope();
    }

    public ShopCarMessageDao getShopCarMessageDao() {
        return shopCarMessageDao;
    }

}
